### ISSUE TITLE
Can't find plugin in Obsidian store

### ISSUE THREAD

**Issue by ChucKN0risK** [1C0D/duplicate-line-obsidian#1]
Hi there,

I couldn't find this plugin in the Obsidian store nor a way to install it from this repo.

![image](https://user-images.githubusercontent.com/3913276/193524295-5b111b3d-1a7c-4ab4-803b-4e9e31686583.png)

Did I miss something?

Thanks in advance ;)

**Comment by 1C0D** [comment]
they are a lot of plugins waiting to be accepted, I think...
click on releases on the right of the main page, then on assets, and you download the 2 first files. then you go in your .obsidian folder > plugins > and you create a folder named duplicate-line and you past the 2 files in. restart your obsidian if opened and enable the plugin.

**Comment by 1C0D** [comment]
explanations here too https://forum.obsidian.md/t/plugins-mini-faq/7737

**Comment by ChucKN0risK** [comment]
Just installed it through the store. Thanks again 🙏
