### ISSUE TITLE
Can we have up/down seperately (like in VS code)

### ISSUE THREAD

**Issue by eikowagenknecht** [1C0D/duplicate-line-obsidian#3]
I always use Shift + Alt + Up and Shift + Alt + Down (VS Code). Can we have this here as well? I know it's only a minor difference (where the cursor is at the end of the action) but still it would be nice :-)

**Comment by 1C0D** [comment]
I don't get the utility of this function? Result is the same, except final cursor(s) position? In what situation is it useful?

**Comment by eikowagenknecht** [comment]
It‘s useful because either you want to edit the upper duplicate line after duplicating or the lower duplicate line.

Yes, it saves only one keypress, but since most code editors have this functionality, it‘s engrained in my muscle memory and nagging at me when it‘s not working 😅

**Comment by 1C0D** [comment]
ok done. even if it broke my head 🥵

**Comment by eikowagenknecht** [comment]
Thank you ❤️
