### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by simonfossom** [1C0D/duplicate-line-obsidian#5]
There is no icon in command pallete, so when adding it to mobile quick actions there's question mark (there are many actions with questionmarks. basically all that don't put icon)

**Comment by simonfossom** [comment]
Hi, 
thanks for this great timesaving plug-in.
This small thing would make great difference for me.
Many thanks!

**Comment by 1C0D** [comment]
oh sry notifications seem to be turned off. I will have a look at this

**Comment by 1C0D** [comment]
I did a fix for this problem. tell me if it's ok

**Comment by simonfossom** [comment]
I'm afraid not 🤔
After the update in mobile toolbar still shows question mark.
![IMG_20231128_084139](https://github.com/1C0D/duplicate-line-obsidian/assets/8134850/6d769481-3641-43cb-bcd9-5ac182bc46e1)

**Comment by 1C0D** [comment]
ok was late. I forgot a line. Now should work. thks for the picture to show me. Does the "+" allow creating an icon? I'm curious.

**Comment by 1C0D** [comment]
Version 2.2.1

Ok was late. I forgot a line. Now should work. thks for the picture. Does the "+" allow creating an icon? I'm curious.

**Comment by simonfossom** [comment]
Great thanks.
But now some commands have icon and some don't.

> Does the "+" allow creating an icon?  

I wish... It's for adding and removing commands from mobile toolbar. 

Here's the video of it.

https://github.com/1C0D/duplicate-line-obsidian/assets/8134850/ab975a65-9c8f-44c3-ae4b-076156b137a0

**Comment by 1C0D** [comment]
version 2.2.2

I did an update to remove commands when turning off a setting option (command and  shortcut not appearing.)
It could help to limit the number of command to see better
But I don't see a reason why duplicate line down/up are not appearing. The icon should be 
![image](https://github.com/1C0D/duplicate-line-obsidian/assets/63018905/18bb600b-486d-4d56-91ce-bf0d9e22458a)
and the other one up

it doesn't seem to be a duplicate in your icons.
do some tries after the update and also maybe uninstall reinstall
if it's still not working I can try to modify the icon by another one to see if it makes a difference. but logically all lucid icons should work.

**Comment by simonfossom** [comment]
After reinstalling I had this commands :

![Screenshot_2023-11-28-18-01-48-48_51606159b24eff83e24a54116878fe3e](https://github.com/1C0D/duplicate-line-obsidian/assets/8134850/1367c48f-e9dc-4860-ae91-5cc41fcfcd7a)

then I turned all off and had these:

![Screenshot_2023-11-28-18-04-34-50_51606159b24eff83e24a54116878fe3e](https://github.com/1C0D/duplicate-line-obsidian/assets/8134850/aa197fb0-b5b1-47cb-932b-c00b0aff671c)

and when I turned back all on it stayed like that.

very odd... 🤔

**Comment by 1C0D** [comment]
I found the cause on the discord, all lucid icons are not in Obsidian. I get to create them from the SGV code given with the icon. Working on it. I was on a rush, now that's ok.

**Comment by 1C0D** [comment]
ok I created missing icons

**Comment by simonfossom** [comment]
Perfect! 👌
Thanks a lot 🙏

**Comment by 1C0D** [comment]
Honestly, you have been a great help there. Thank you

**Comment by cwriasir** [comment]
Now comes a new problem: some of the new icons are incorrect or missing, specifically Duplicate Line Up, Add Next Occurrence, and Duplicate Selection Right. Might want to check if the icons are assigned correctly.
![Screenshot_2023-12-04-22-45-13](https://github.com/1C0D/duplicate-line-obsidian/assets/59495978/7137bf23-00bc-43e2-96e9-18bfb41527a1)

**Comment by 1C0D** [comment]
@cwriasir thks for your pull request. Even the icon.s file was missing. Apparently I missed a push.
Should be ok now.
